services:
  - type: web
    name: visitor-pass-management
    env: node
    plan: free
    buildCommand: npm install && npm --prefix frontend install --include=dev && npm --prefix frontend run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
